module.exports = {
  apps: [{
    name: 'backend-service-main',
    script: './build/index.js',
    args: '',
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: '1G',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    min_uptime: '24h',
    max_restarts: 50,
    out_file: './logs/server_1.log',
    error_file: './logs/server_1.log',
    merge_logs: true,
    env: {
      PORT: 8080,
      IMPORTER_ENDPOINT: 'http://localhost:8201/api/txs/signed',
      DB: 'icarus_mainnet_1',
      NODE_ENV: 'production',
    },
    env_development: {
      NODE_ENV: 'development',
    },
  },
  {
    name: 'backend-service-backup',
    script: './build/index.js',
    args: '',
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: '1G',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    min_uptime: '24h',
    max_restarts: 50,
    out_file: './logs/server_2.log',
    error_file: './logs/server_2.log',
    merge_logs: true,
    env: {
      PORT: 8081,
      IMPORTER_ENDPOINT: 'http://localhost:8202/api/txs/signed',
      DB: 'icarus_mainnet_2',
      NODE_ENV: 'production',
    },
    env_development: {
      NODE_ENV: 'development',
    },
  }],
}
